export  enum RoleType {
  PSC1 = "PSCA",
  PSE1 = "PSE1",
  PSE2 = "PSE2",
  PSE1_CYCLISTE = "PSE1 Cycliste",
  PSE2_CYCLISTE = "PSE2 Cycliste",
  PSE1_CAVALIER = "PSE1 Cavalier",
  PSE2_CAVALIER = "PSE2 Cavalier",
  CI = "CI",
  CDP = "CI (Chef de Poste)",
  CHEF_SECTEUR = "Chef de Secteur",
  CDPMGE = "Chef de Poste Moyenne et Grande Envergure",
  CI_BSPP = "CI BSPP",
  CI_ALPHA = "CI Alpha",
  CH_VPSP = "Chauffeur",
  CH_VL = "Chauffeur VL",
  CH_QUAD = "Chauffeur Quad",
  INFIRMIER = "Infirmier",
  MEDECIN = "Médecin",
  DLUS = "DLUS",
  REGULATEUR = "Régulateur",
  REGULATEUR_TERRAIN = "Régulateur Terrain",
  AIDE_REGULATEUR = "Aide Régulateur",
  LOGISTICIEN = "Logisticien",
  ONYX = "Onyx",
  PARTICIPANT = "Participant",
  PARTICIPANT_EXT = "Participant Extérieur"
}
