steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    timeout: "500s"
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--prod']
    timeout: "500s"
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--project', 'crf7505-front-prod']
    timeout: "500s"
